### 
GET  http://localhost:3000/api/v1/artists HTTP/1.1
//Content-Type: application/json

###
GET  http://localhost:3000/api/v1/artists/63eee74b21e1be49247c6a5b HTTP/1.1
//Content-Type: application/json

###
POST http://localhost:3000/api/v1/artists/ HTTP/1.1
Content-Type: application/json

{
    "artistGenre": "Blues", 
    "artistName": "Dannie",
    "artistLastname": "Wilde",
    "artistCountry": "Estados Unidos"
}

###
DELETE  http://localhost:3000/api/v1/artists/63eee6c621e1be49247c6a4d HTTP/1.1
Content-Type: application/json
